// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig , env  } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations (bypasses Supabase connection pooler)
    // Use DATABASE_URL (pooler) in PrismaClient at runtime
    url: env('DIRECT_URL'),
  },
});
